### ISSUE TITLE
custom Policy link text not working

### ISSUE THREAD

**Issue by DiegoVallejoDev** [glowhub-dev/glowhub#1]
Hello, I found GlowHub by accident the other day and decided to give it a try and I want to congratulate you on your work, it has made my job much easier

now, let's go back to the bug:

this is the configuration of the cookie message:
![image](https://user-images.githubusercontent.com/8756873/118738682-36e51300-b80d-11eb-9a9a-b2c0ace065ba.png)

this is the expected preview:
![image](https://user-images.githubusercontent.com/8756873/118738789-7875be00-b80d-11eb-9fb8-c49207c4f299.png)

And here is on the website:

![image](https://user-images.githubusercontent.com/8756873/118738842-9cd19a80-b80d-11eb-9095-d50ad9643325.png)

**Comment by manucaralmo** [comment]
Hi! Thank you very much Diego! we will review the problem and solve it as soon as possible

**Comment by manucaralmo** [comment]
@DiegoVallejoDev Try now changing your script to version 1.0.2
`<script src="https://cdn.jsdelivr.net/gh/glowhub-dev/glowhub-scripts@1.0.2/glowHub.min.js"></script>
<script> `
You can also go to your dashboard in GlowHub and copy the code again.
Thank you!
